// Vietnamese translations
export default {
  common: {
    appName: "Workly",
    save: "Lưu",
    cancel: "Hủy",
    delete: "Xóa",
    edit: "Sửa",
    add: "Thêm",
    confirm: "Xác nhận",
    yes: "Có",
    no: "Không",
    ok: "OK",
    loading: "Đang tải...",
    error: "Lỗi",
    success: "Thành công",
    retry: "Thử lại",
    warning: "Cảnh báo",
    viewAll: "Xem tất cả",
    helpCenter: "Trung tâm trợ giúp",
    support: "Hỗ trợ",
    locale: "vi-VN",
  },
  home: {
    todayShifts: "Ca làm việc hôm nay",
    weeklySchedule: "Lịch tuần này",
    weather: "Thời tiết",
    notes: "Ghi chú công việc",
    noShiftsToday: "Không có ca làm việc nào hôm nay",
    addNewShift: "Thêm ca mới",
    noNotes: "Không có ghi chú nào",
    addNewNote: "Thêm ghi chú mới",
    checkInStatus: {
      notCheckedIn: "Chưa check-in",
      checkedInNotOut: "Đã check-in, chưa check-out",
      checkedInAndOut: "Đã check-in và check-out",
    },
    logGoWork: "Đi làm",
    logCheckIn: "Check-in",
    logPunch: "Punch",
    logCheckOut: "Check-out",
    logComplete: "Hoàn thành",
    workingFor: "Đang làm việc trong {duration}",
    welcomeMessage:
      "Chào mừng đến với Workly, ứng dụng quản lý ca làm việc cá nhân của bạn!",
    weatherAlert: "Thời tiết hiện tại: {temperature}°C - {condition}",
    shiftInstructions:
      "Nhấn 'Đi làm' để bắt đầu ca làm việc, sau đó sử dụng 'Check In' khi bạn đến nơi.",
    reminderNote: "Bạn có {count} lời nhắc được lên lịch cho hôm nay.",
    helpText: "Cần trợ giúp? Truy cập trung tâm trợ giúp hoặc liên hệ hỗ trợ.",
  },
  shifts: {
    shiftList: "Danh sách ca làm việc",
    addShift: "Thêm ca làm việc",
    editShift: "Sửa ca làm việc",
    shiftDetails: "Chi tiết ca làm việc",
    shiftName: "Tên ca làm việc",
    startTime: "Thời gian bắt đầu",
    endTime: "Thời gian kết thúc",
    daysApplied: "Các ngày áp dụng",
    location: "Địa điểm",
    notes: "Ghi chú",
    deleteShift: "Xóa ca làm việc",
    deleteShiftConfirm: "Bạn có chắc chắn muốn xóa ca làm việc này?",
    deleteConfirm: "Xác nhận xóa",
    deleteConfirmMessage: 'Bạn có chắc chắn muốn xóa ca "{name}" không?',
    noShifts: "Không có ca làm việc nào",
    invalidTimeRange: "Thời gian kết thúc phải sau thời gian bắt đầu",
    shiftSaved: "Ca làm việc đã được lưu",
    shiftDeleted: "Ca làm việc đã được xóa",
    selectDays: "Chọn các ngày",
    showPunchButton: "Hiển thị nút Punch",
    shiftTip:
      "Đối với ca làm việc qua đêm, đặt thời gian kết thúc sau nửa đêm.",
    breakExplanation:
      "Thời gian nghỉ {duration} phút sẽ tự động được trừ khỏi giờ làm việc của bạn.",
    break: "Nghỉ",
    addShiftPrompt: "Nhấn nút bên dưới để thêm ca mới",
  },
  settings: {
    settings: "Cài đặt",
    interface: "Giao diện",
    notifications: "Thông báo",
    weather: "Thời tiết",
    data: "Dữ liệu",
    other: "Khác",
    multiButtonMode: "Chế độ nút đa chức năng",
    firstDayOfWeek: "Ngày đầu tuần",
    timeFormat: "Định dạng thời gian",
    theme: "Giao diện",
    alarmSound: "Âm thanh báo thức",
    alarmVibration: "Rung khi báo thức",
    shiftChangeReminder: "Nhắc nhở thay đổi ca làm việc",
    weatherWarning: "Cảnh báo thời tiết",
    updateLocation: "Cập nhật vị trí",
    backupData: "Sao lưu dữ liệu",
    restoreData: "Khôi phục dữ liệu",
    language: "Ngôn ngữ",
    about: "Giới thiệu",
    hapticFeedback: "Phản hồi xúc giác",
    switchToLanguage: "Chuyển sang {language}",
    options: {
      full: "Đầy đủ",
      simple: "Đơn giản",
      monday: "Thứ Hai",
      sunday: "Chủ Nhật",
      hour24: "24 giờ",
      hour12: "12 giờ",
      light: "Sáng",
      dark: "Tối",
      system: "Hệ thống",
      askWeekly: "Hỏi hàng tuần",
      askDaily: "Hỏi hàng ngày",
      auto: "Tự động",
      off: "Tắt",
      vietnamese: "Tiếng Việt",
      english: "Tiếng Anh",
    },
    descriptions: {
      multiButtonMode:
        "Chọn kiểu hiển thị của nút đa chức năng trên màn hình chính",
      firstDayOfWeek: "Chọn ngày đầu tiên của tuần trong lịch",
      timeFormat: "Chọn định dạng hiển thị thời gian",
      theme: "Chọn giao diện ứng dụng",
      alarmSound: "Bật/tắt âm thanh cho các thông báo báo thức",
      alarmVibration: "Bật/tắt rung cho các thông báo báo thức",
      hapticFeedback: "Bật/tắt phản hồi xúc giác khi nhấn các nút",
      shiftChangeReminder:
        "Cài đặt nhắc nhở khi ca làm việc sắp bắt đầu hoặc kết thúc",
      weatherWarning: "Nhận cảnh báo về điều kiện thời tiết khắc nghiệt",
      language: "Thay đổi ngôn ngữ hiển thị của ứng dụng",
    },
  },
  attendance: {
    checkIn: "Check In",
    checkOut: "Check Out",
    attendanceHistory: "Lịch sử chấm công",
    noAttendanceData: "Chưa có dữ liệu chấm công",
    checkInSuccess: "Check-in thành công",
    checkOutSuccess: "Check-out thành công",
    alreadyCheckedIn: "Bạn đã check-in cho ca làm việc này rồi",
    alreadyCheckedOut: "Bạn đã check-out cho ca làm việc này rồi",
    needCheckInFirst: "Bạn cần check-in trước khi check-out",
    noShiftsToCheckIn: "Không có ca làm việc nào được lên lịch cho hôm nay",
    chooseShift: "Chọn ca làm việc",
    multipleShiftsPrompt:
      "Bạn có nhiều ca làm việc hôm nay. Vui lòng chọn ca để check-in:",
    multipleCheckInsPrompt:
      "Bạn đã check-in cho nhiều ca làm việc. Vui lòng chọn ca để check-out:",
  },
  weather: {
    currentLocation: "Vị trí hiện tại",
    updatedAt: "Cập nhật lúc",
    humidity: "Độ ẩm",
    wind: "Gió",
    loadingWeather: "Đang tải dữ liệu thời tiết...",
    locationDenied: "Quyền truy cập vị trí bị từ chối",
    weatherError: "Không thể lấy dữ liệu thời tiết. Vui lòng thử lại sau.",
    noWeatherData: "Không có dữ liệu thời tiết",
    loadData: "Tải dữ liệu",
    update: "Cập nhật",
    updatedSuccessfully: "Dữ liệu thời tiết đã được cập nhật thành công",
    warnings: {
      highTemp: "Nhiệt độ cao bất thường, hãy uống nhiều nước",
      lowTemp: "Nhiệt độ thấp, hãy mặc ấm",
      thunderstorm: "Có giông bão, hãy cẩn thận khi di chuyển",
      heavyRain: "Mưa lớn, có thể gây ngập lụt",
    },
    forecast: "Dự báo 5 ngày",
    forecastError: "Không thể lấy dữ liệu dự báo",
    today: "Hôm nay",
    tomorrow: "Ngày mai",
  },
  notes: {
    notes: "Ghi chú",
    addNote: "Thêm ghi chú",
    editNote: "Sửa ghi chú",
    deleteNote: "Xóa ghi chú",
    deleteNoteConfirm: "Bạn có chắc chắn muốn xóa ghi chú này?",
    saveConfirm: "Lưu ghi chú này?",
    title: "Tiêu đề",
    content: "Nội dung",
    reminderTime: "Thời gian nhắc nhở",
    reminderDays: "Các ngày nhắc nhở",
    associatedShifts: "Ca làm việc liên quan",
    noNotes: "Không có ghi chú nào",
    noteSaved: "Ghi chú đã được lưu",
    noteDeleted: "Ghi chú đã được xóa",
    today: "Hôm nay",
    tomorrow: "Ngày mai",
    titleRequired: "Tiêu đề là bắt buộc",
    duplicateNote: "Đã tồn tại một ghi chú với tiêu đề tương tự",
    selectDays: "Chọn các ngày",
    selectShifts: "Chọn ca làm việc",
    addNotePrompt: "Thêm ghi chú mới",
    workNotes: "Ghi chú công việc",
    characterCount: "{current}/{max} ký tự",
    validation: {
      titleRequired: "Tiêu đề là bắt buộc",
      contentRequired: "Nội dung là bắt buộc",
      reminderTimeRequired: "Thời gian nhắc nhở là bắt buộc",
      reminderDaysRequired: "Cần chọn ít nhất một ngày nhắc nhở",
      duplicateNote: "Đã tồn tại một ghi chú với tiêu đề tương tự",
    },
  },
  backup: {
    backupRestore: "Sao lưu & Phục hồi",
    backupData: "Sao lưu dữ liệu",
    restoreData: "Phục hồi dữ liệu",
    backupDescription:
      "Xuất dữ liệu của bạn để sao lưu hoặc chuyển sang thiết bị khác. Tệp sao lưu sẽ bao gồm tất cả cài đặt, ca làm việc, dữ liệu chấm công và ghi chú.",
    restoreDescription:
      "Nhập dữ liệu từ tệp sao lưu đã xuất trước đó. Lưu ý: Dữ liệu hiện tại sẽ bị ghi đè khi bạn nhập dữ liệu mới.",
    exportData: "Xuất dữ liệu",
    importData: "Nhập dữ liệu",
    backupWarning:
      "Hãy sao lưu dữ liệu thường xuyên để tránh mất dữ liệu khi thay đổi thiết bị hoặc gỡ cài đặt ứng dụng.",
    confirmRestore: "Xác nhận nhập dữ liệu",
    confirmRestoreMessage:
      "Dữ liệu hiện tại sẽ bị ghi đè. Bạn có chắc chắn muốn tiếp tục?",
    importSuccess: "Dữ liệu đã được nhập thành công.",
    importError:
      "Không thể nhập dữ liệu. Tệp có thể bị hỏng hoặc sai định dạng.",
    sharingNotAvailable: "Không thể chia sẻ",
    sharingNotAvailableMessage: "Thiết bị của bạn không hỗ trợ chia sẻ tệp.",
    processing: "Đang xử lý...",
  },
  time: {
    hour: "giờ",
    hours: "giờ",
    minute: "phút",
    minutes: "phút",
    duration: "{hours} giờ {minutes} phút",
    durationHoursOnly: "{hours} giờ",
    durationMinutesOnly: "{minutes} phút",
  },
  alarm: {
    alarm: "Báo thức",
    timeToWork: "Đến giờ làm việc",
    shiftStartingSoon: "Ca làm việc {name} sẽ bắt đầu trong {minutes} phút.",
    shiftEndingSoon: "Ca làm việc {name} sẽ kết thúc trong {minutes} phút.",
    dismissAlarm: "Tắt báo thức",
    displayTime: "Thời gian hiển thị",
    sounds: {
      standard: "Chuông chuẩn",
      gentle: "Chuông nhẹ nhàng",
      emergency: "Chuông khẩn cấp",
    },
  },
};
